id: PFFA8BB2A
initial_creation_type: ocr
source_metadata:
  volumes:
    4536daf1eba040eca8d7663aa42cea51:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: སྲིད་པ་ལས་འདས་པའི་གཏམ།
      total_pages: 1144
      volume_number: 96
